name: converthis_unit
description: Dart Unit Conversion
version: 0.0.1
homepage: https://github.com/ChrisStayte/converthis_unit

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  decimal: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
